package shop.company.entity;

// Generated 2010-6-18 15:00:02 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AuthPurview generated by hbm2java
 */
@Entity
@Table(name = "auth_purview")
public class AuthPurview implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String purviewId;
	private AuthPurview authPurview;
	private String purviewName;
	private String purviewUrl;
	private String purviewImage;
	private String purviewType;
	private String purviewMask;
	private String purviewComment;
	private String active;
	//private Set<AuthRole> authRoles = new HashSet<AuthRole>(0);
	private Set<AuthPurview> authPurviews = new HashSet<AuthPurview>(0);

	public AuthPurview() {
	}

	public AuthPurview(String purviewId) {
		this.purviewId = purviewId;
	}

	public AuthPurview(String purviewId, AuthPurview authPurview,
			String purviewName, String purviewUrl, String purviewImage,
			String purviewType, String purviewMask, String purviewComment,
			/*Set<AuthRole> authRoles,*/ Set<AuthPurview> authPurviews) {
		this.purviewId = purviewId;
		this.authPurview = authPurview;
		this.purviewName = purviewName;
		this.purviewUrl = purviewUrl;
		this.purviewImage = purviewImage;
		this.purviewType = purviewType;
		this.purviewMask = purviewMask;
		this.purviewComment = purviewComment;
		//this.authRoles = authRoles;
		this.authPurviews = authPurviews;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "PURVIEW_ID", unique = true, nullable = false, length = 50)
	public String getPurviewId() {
		return this.purviewId;
	}

	public void setPurviewId(String purviewId) {
		this.purviewId = purviewId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PURVIEW_UPID")
	public AuthPurview getAuthPurview() {
		return this.authPurview;
	}

	public void setAuthPurview(AuthPurview authPurview) {
		this.authPurview = authPurview;
	}

	@Column(name = "PURVIEW_NAME", length = 50)
	public String getPurviewName() {
		return this.purviewName;
	}

	public void setPurviewName(String purviewName) {
		this.purviewName = purviewName;
	}

	@Column(name = "PURVIEW_URL", length = 50)
	public String getPurviewUrl() {
		return this.purviewUrl;
	}

	public void setPurviewUrl(String purviewUrl) {
		this.purviewUrl = purviewUrl;
	}

	@Column(name = "PURVIEW_IMAGE", length = 5)
	public String getPurviewImage() {
		return this.purviewImage;
	}

	public void setPurviewImage(String purviewImage) {
		this.purviewImage = purviewImage;
	}

	@Column(name = "PURVIEW_TYPE", length = 50)
	public String getPurviewType() {
		return this.purviewType;
	}

	public void setPurviewType(String purviewType) {
		this.purviewType = purviewType;
	}

	@Column(name = "PURVIEW_MASK", length = 50)
	public String getPurviewMask() {
		return this.purviewMask;
	}

	public void setPurviewMask(String purviewMask) {
		this.purviewMask = purviewMask;
	}

	@Column(name = "PURVIEW_COMMENT", length = 250)
	public String getPurviewComment() {
		return this.purviewComment;
	}

	public void setPurviewComment(String purviewComment) {
		this.purviewComment = purviewComment;
	}

    @Column(name = "ACTIVE", length = 4 )
    public String getActive() {
        return active;
    }

    public void setActive(String active) {
        this.active = active;
    }

    /*@ManyToMany(fetch = FetchType.LAZY, mappedBy = "authPurviews")
	public Set<AuthRole> getAuthRoles() {
		return this.authRoles;
	}

	public void setAuthRoles(Set<AuthRole> authRoles) {
		this.authRoles = authRoles;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authPurview",targetEntity=AuthPurview.class)
	public Set<AuthPurview> getAuthPurviews() {
		return this.authPurviews;
	}

	public void setAuthPurviews(Set<AuthPurview> authPurviews) {
		this.authPurviews = authPurviews;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((purviewId == null) ? 0 : purviewId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AuthPurview other = (AuthPurview) obj;
		if (purviewId == null) {
			if (other.purviewId != null)
				return false;
		} else if (!purviewId.equals(other.purviewId))
			return false;
		return true;
	}

}
