package shop.company.entity;

// Generated 2010-6-18 15:00:02 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * AuthUsers generated by hbm2java
 */
@Entity
@Table(name = "auth_user")
public class AuthUser implements java.io.Serializable {

	protected String userName;
	protected String userRealname;
	protected String userPassword;
	protected String userPassword2;
	protected String userComment;
	protected Set<AuthRole> authRoles = new HashSet<AuthRole>(0);

	public AuthUser() {
	}

	public AuthUser(String userName) {
		this.userName = userName;
	}

	public AuthUser(String userName, String userRealname, String userPassword,
			Set<AuthRole> authRoles) {
		this.userName = userName;
		this.userRealname = userRealname;
		this.userPassword = userPassword;
		this.authRoles = authRoles;
	}

	@Id
	@Column(name = "USER_NAME", unique = true, nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "USER_REALNAME", length = 50)
	public String getUserRealname() {
		return this.userRealname;
	}

	public void setUserRealname(String userRealname) {
		this.userRealname = userRealname;
	}

	@Column(name = "USER_PASSWORD", length = 50)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "USER_COMMENT", length = 255)
	public String getUserComment() {
		return userComment;
	}

	public void setUserComment(String userComment) {
		this.userComment = userComment;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "auth_user_role", joinColumns = { @JoinColumn(name = "USER_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ROLE_ID", nullable = false, updatable = false) })
	public Set<AuthRole> getAuthRoles() {
		return this.authRoles;
	}

	public void setAuthRoles(Set<AuthRole> authRoles) {
		this.authRoles = authRoles;
	}
	@Column(name = "USER_PASSWORD2", length = 50)
	public String getUserPassword2() {
		return userPassword2;
	}

	public void setUserPassword2(String userPassword2) {
		this.userPassword2 = userPassword2;
	}

}
