package shop.company.entity;

// Generated 2010-11-23 17:24:58 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SiteParameter generated by hbm2java
 */
@Entity
@Table(name = "site_parameter")
public class SiteParameter implements java.io.Serializable {

	private String paramKey;
	private String paramName;
	private String paramComment;
	
	private Set<SiteParameterItem> siteParameterItems;

	public SiteParameter() {
	}

	public SiteParameter(String paramKey) {
		this.paramKey = paramKey;
	}

	public SiteParameter(String paramKey, String paramName, String paramComment) {
		this.paramKey = paramKey;
		this.paramName = paramName;
		this.paramComment = paramComment;
	}

	@Id
	@Column(name = "param_key", unique = true, nullable = false, length = 50)
	public String getParamKey() {
		return this.paramKey;
	}

	public void setParamKey(String paramKey) {
		this.paramKey = paramKey;
	}

	@Column(name = "param_name", length = 50)
	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	@Column(name = "param_comment")
	public String getParamComment() {
		return this.paramComment;
	}

	public void setParamComment(String paramComment) {
		this.paramComment = paramComment;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, targetEntity = SiteParameterItem.class)
	@JoinColumn(name="param_key")
	public Set<SiteParameterItem> getSiteParameterItems() {
		return siteParameterItems;
	}

	public void setSiteParameterItems(Set<SiteParameterItem> siteParameterItems) {
		this.siteParameterItems = siteParameterItems;
	}
	
}
