package shop.company.entity;

// Generated 2010-11-23 17:24:58 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SiteParameterItem generated by hbm2java
 */
@Entity
@Table(name = "site_parameter_item", uniqueConstraints = @UniqueConstraint(columnNames = "param_key"))
public class SiteParameterItem implements java.io.Serializable {

	private Integer paramItemId;
	private String paramKey;
	private String paramItemValue;
	private String paramItemValue1;
	private String paramItemValue2;
	private String paramItemValue3;
	private String paramItemName;
	private String paramItemComment;

	public SiteParameterItem() {
	}

	public SiteParameterItem(String paramKey, String paramItemValue,
                             String paramItemName) {
		this.paramKey = paramKey;
		this.paramItemValue = paramItemValue;
		this.paramItemName = paramItemName;
	}

	public SiteParameterItem(String paramKey, String paramItemValue,
                             String paramItemName, String paramItemComment) {
		this.paramKey = paramKey;
		this.paramItemValue = paramItemValue;
		this.paramItemName = paramItemName;
		this.paramItemComment = paramItemComment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "param_item_id", nullable = false)
	public Integer getParamItemId() {
		return this.paramItemId;
	}

	public void setParamItemId(Integer paramItemId) {
		this.paramItemId = paramItemId;
	}

	@Column(name = "param_key", unique = true, nullable = false, length = 50)
	public String getParamKey() {
		return this.paramKey;
	}

	public void setParamKey(String paramKey) {
		this.paramKey = paramKey;
	}

	@Column(name = "param_item_value", nullable = false)
	public String getParamItemValue() {
		return this.paramItemValue;
	}

	public void setParamItemValue(String paramItemValue) {
		this.paramItemValue = paramItemValue;
	}

	@Column(name = "param_item_value1")
	public String getParamItemValue1() {
		return this.paramItemValue1;
	}

	public void setParamItemValue1(String paramItemValue1) {
		this.paramItemValue1 = paramItemValue1;
	}

	@Column(name = "param_item_value2")
	public String getParamItemValue2() {
		return this.paramItemValue2;
	}

	public void setParamItemValue2(String paramItemValue2) {
		this.paramItemValue2 = paramItemValue2;
	}

	@Column(name = "param_item_value3")
	public String getParamItemValue3() {
		return this.paramItemValue3;
	}

	public void setParamItemValue3(String paramItemValue3) {
		this.paramItemValue3 = paramItemValue3;
	}

	@Column(name = "param_item_name", nullable = false, length = 50)
	public String getParamItemName() {
		return this.paramItemName;
	}

	public void setParamItemName(String paramItemName) {
		this.paramItemName = paramItemName;
	}

	@Column(name = "param_item_comment")
	public String getParamItemComment() {
		return this.paramItemComment;
	}

	public void setParamItemComment(String paramItemComment) {
		this.paramItemComment = paramItemComment;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((paramItemName == null) ? 0 : paramItemName.hashCode());
		result = prime * result
				+ ((paramKey == null) ? 0 : paramKey.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SiteParameterItem other = (SiteParameterItem) obj;
		if (paramItemName == null) {
			if (other.paramItemName != null)
				return false;
		} else if (!paramItemName.equals(other.paramItemName))
			return false;
		if (paramKey == null) {
			if (other.paramKey != null)
				return false;
		} else if (!paramKey.equals(other.paramKey))
			return false;
		return true;
	}
	
	

}
