package shop.company.entity;

// Generated 2010-6-18 15:00:02 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SystemDictionaryItem generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_DICTIONARY_ITEM")
public class SystemDictionaryItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer dictItemId;
	private String dictId;
	private String dictItemKey;
	private String dictItemValue;
	private String dictItemComment;
	

	public SystemDictionaryItem() {
	}

	public SystemDictionaryItem(Integer dictItemId) {
		this.dictItemId = dictItemId;
	}

	public SystemDictionaryItem(Integer dictItemId, String dictItemKey,
			String dictItemValue, String dictItemComment) {
		this.dictItemId = dictItemId;
		this.dictItemKey = dictItemKey;
		this.dictItemValue = dictItemValue;
		this.dictItemComment = dictItemComment;
	}

	@Id
	@Column(name = "DICT_ITEM_ID", unique = true, nullable = false, precision = 8, scale = 0)
	public Integer getDictItemId() {
		return this.dictItemId;
	}

	public void setDictItemId(Integer dictItemId) {
		this.dictItemId = dictItemId;
	}

	@Column(name = "DICT_ITEM_KEY", length = 250)
	public String getDictItemKey() {
		return this.dictItemKey;
	}

	public void setDictItemKey(String dictItemKey) {
		this.dictItemKey = dictItemKey;
	}

	@Column(name = "DICT_ITEM_VALUE", length = 50)
	public String getDictItemValue() {
		return this.dictItemValue;
	}

	public void setDictItemValue(String dictItemValue) {
		this.dictItemValue = dictItemValue;
	}

	@Column(name = "DICT_ITEM_COMMENT", length = 250)
	public String getDictItemComment() {
		return this.dictItemComment;
	}

	public void setDictItemComment(String dictItemComment) {
		this.dictItemComment = dictItemComment;
	}

	@Column(name = "DICT_ID", length = 50)
	public String getDictId() {
		return dictId;
	}

	public void setDictId(String dictId) {
		this.dictId = dictId;
	}
	
	

}
