package shop.company.entity;

// Generated 2010-12-31 21:47:38 by Hibernate Tools 3.4.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * SystemLoginLog generated by hbm2java
 */
@Entity
@Table(name = "system_login_log")
public class SystemLoginLog implements java.io.Serializable {

	private Integer loginId;
	private String memId;
	private String loginIp;
	private String loginAddr;
	private String loginType;
	private Date loginTime;
	private Date logoutTime;
	private Date loginTime2;
	private Date logoutTime2;
	private String loginComment;

	private List<SystemOperationLog> operationLogs;

	public SystemLoginLog() {
	}

	public SystemLoginLog(String memId, String loginIp, String loginAddr,
			String loginType, Date loginTime, Date logoutTime,
			String loginComment) {
		this.memId = memId;
		this.loginIp = loginIp;
		this.loginAddr = loginAddr;
		this.loginType = loginType;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
		this.loginComment = loginComment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "login_id", nullable = false)
	public Integer getLoginId() {
		return this.loginId;
	}

	public void setLoginId(Integer loginId) {
		this.loginId = loginId;
	}

	@Column(name = "mem_id", length = 50)
	public String getMemId() {
		return this.memId;
	}

	public void setMemId(String memId) {
		this.memId = memId;
	}

	@Column(name = "login_ip", length = 50)
	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	@Column(name = "login_addr", length = 50)
	public String getLoginAddr() {
		return this.loginAddr;
	}

	public void setLoginAddr(String loginAddr) {
		this.loginAddr = loginAddr;
	}

	@Column(name = "login_type", length = 50)
	public String getLoginType() {
		return this.loginType;
	}

	public void setLoginType(String loginType) {
		this.loginType = loginType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_time", length = 19)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logout_time", length = 19)
	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	@Column(name = "login_comment", length = 50)
	public String getLoginComment() {
		return this.loginComment;
	}

	public void setLoginComment(String loginComment) {
		this.loginComment = loginComment;
	}

	@Transient
	public List<SystemOperationLog> getOperationLogs() {
		return operationLogs;
	}

	public void setOperationLogs(List<SystemOperationLog> operationLogs) {
		this.operationLogs = operationLogs;
	}

	@Transient
	public Date getLoginTime2() {
		return loginTime2;
	}

	public void setLoginTime2(Date loginTime2) {
		this.loginTime2 = loginTime2;
	}

	@Transient
	public Date getLogoutTime2() {
		return logoutTime2;
	}

	public void setLogoutTime2(Date logoutTime2) {
		this.logoutTime2 = logoutTime2;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((loginId == null) ? 0 : loginId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SystemLoginLog other = (SystemLoginLog) obj;
		if (loginId == null) {
			if (other.loginId != null)
				return false;
		} else if (!loginId.equals(other.loginId))
			return false;
		return true;
	}

}
