package shop.company.entity;

// Generated 2010-12-31 0:34:17 by Hibernate Tools 3.4.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * MemOperationLog generated by hbm2java
 */
@Entity
@Table(name = "system_operation_log")
public class SystemOperationLog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer opId;
	private Integer loginId;
	private Date startTime;
	private Date endTime;
	private Date startTime2;
	private Date endTime2;
	private String opIp;
	private String opAddr;
	private String userId;
	private String opType;
	private String opComment;
	private String operation;

	public SystemOperationLog() {
	}

	public SystemOperationLog(Date startTime, Date endTime, String opIp,
			String opAddr, String userId, String opType, String opComment) {
		this.startTime = startTime;
		this.endTime = endTime;
		this.opIp = opIp;
		this.opAddr = opAddr;
		this.userId = userId;
		this.opType = opType;
		this.opComment = opComment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "op_id", nullable = false)
	public Integer getOpId() {
		return this.opId;
	}

	public void setOpId(Integer opId) {
		this.opId = opId;
	}
	
	@Column(name = "login_id")
	public Integer getLoginId() {
		return this.loginId;
	}
	
	public void setLoginId(Integer loginId) {
		this.loginId = loginId;
	}

	@Column(name = "start_time", length = 20)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Column(name = "end_time", length = 20)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "op_ip", length = 50)
	public String getOpIp() {
		return this.opIp;
	}

	public void setOpIp(String opIp) {
		this.opIp = opIp;
	}

	@Column(name = "op_addr", length = 50)
	public String getOpAddr() {
		return this.opAddr;
	}

	public void setOpAddr(String opAddr) {
		this.opAddr = opAddr;
	}

	@Column(name = "user_id", length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "op_type", length = 50)
	public String getOpType() {
		return this.opType;
	}

	public void setOpType(String opType) {
		this.opType = opType;
	}

	@Column(name = "operation", length = 50)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "op_comment", length = 100)
	public String getOpComment() {
		return this.opComment;
	}

	public void setOpComment(String opComment) {
		this.opComment = opComment;
	}

	@Transient
	public Date getStartTime2() {
		return startTime2;
	}

	public void setStartTime2(Date startTime2) {
		this.startTime2 = startTime2;
	}

	@Transient
	public Date getEndTime2() {
		return endTime2;
	}

	public void setEndTime2(Date endTime2) {
		this.endTime2 = endTime2;
	}
	
}
