package shop.company.entity;

// Generated 2010-6-18 14:57:56 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SystemDictionary generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_DICTIONARY")
public class SystemDictionary implements java.io.Serializable {

	private String dictId;
	private String dictName;
	private String dictComment;
	private Set<SystemDictionaryItem> systemDictionaryItems = new HashSet<SystemDictionaryItem>(
			0);

	public SystemDictionary() {
	}

	public SystemDictionary(String dictId) {
		this.dictId = dictId;
	}

	public SystemDictionary(String dictId, String dictName, String dictComment,
			Set<SystemDictionaryItem> systemDictionaryItems) {
		this.dictId = dictId;
		this.dictName = dictName;
		this.dictComment = dictComment;
		this.systemDictionaryItems = systemDictionaryItems;
	}

	@Id
	@Column(name = "DICT_ID", unique = true, nullable = false, length = 50)
	public String getDictId() {
		return this.dictId;
	}

	public void setDictId(String dictId) {
		this.dictId = dictId;
	}

	@Column(name = "DICT_NAME", length = 50)
	public String getDictName() {
		return this.dictName;
	}

	public void setDictName(String dictName) {
		this.dictName = dictName;
	}

	@Column(name = "DICT_COMMENT", length = 250)
	public String getDictComment() {
		return this.dictComment;
	}

	public void setDictComment(String dictComment) {
		this.dictComment = dictComment;
	}

	@OneToMany(fetch = FetchType.EAGER, targetEntity = SystemDictionaryItem.class)
	@JoinColumn(name="DICT_ID")
	public Set<SystemDictionaryItem> getSystemDictionaryItems() {
		return this.systemDictionaryItems;
	}

	public void setSystemDictionaryItems(
			Set<SystemDictionaryItem> systemDictionaryItems) {
		this.systemDictionaryItems = systemDictionaryItems;
	}

}
