package shop.company.entity;

// Generated 2010-12-8 16:04:30 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * SystemFqa generated by hbm2java
 */
@Entity
@Table(name = "system_fqa")
public class SystemFqa implements java.io.Serializable {

	private Integer fqaId;
	private String fqaQuestion;
	private String fqaQuestionType;
	private String userLevel;
	private String bonusLevel;
	private String repeatConsumeLevel;
	private String rewardStatus;
	private String fqaAnswer;
	private Date createTime;
	private Date createTime2;

	public SystemFqa() {
	}

	public SystemFqa(String fqaQuestion, String fqaQuestionType,
			String userLevel, String bonusLevel, String repeatConsumeLevel,
			String rewardStatus, String fqaAnswer, Date createTime) {
		this.fqaQuestion = fqaQuestion;
		this.fqaQuestionType = fqaQuestionType;
		this.userLevel = userLevel;
		this.bonusLevel = bonusLevel;
		this.repeatConsumeLevel = repeatConsumeLevel;
		this.rewardStatus = rewardStatus;
		this.fqaAnswer = fqaAnswer;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "fqa_id", nullable = false)
	public Integer getFqaId() {
		return this.fqaId;
	}

	public void setFqaId(Integer fqaId) {
		this.fqaId = fqaId;
	}

	@Column(name = "fqa_question", length = 1000)
	public String getFqaQuestion() {
		return this.fqaQuestion;
	}

	public void setFqaQuestion(String fqaQuestion) {
		this.fqaQuestion = fqaQuestion;
	}

	@Column(name = "fqa_question_type", length = 10)
	public String getFqaQuestionType() {
		return this.fqaQuestionType;
	}

	public void setFqaQuestionType(String fqaQuestionType) {
		this.fqaQuestionType = fqaQuestionType;
	}

	@Column(name = "USER_LEVEL", length = 10)
	public String getUserLevel() {
		return this.userLevel;
	}

	public void setUserLevel(String userLevel) {
		this.userLevel = userLevel;
	}

	@Column(name = "BONUS_LEVEL", length = 10)
	public String getBonusLevel() {
		return this.bonusLevel;
	}

	public void setBonusLevel(String bonusLevel) {
		this.bonusLevel = bonusLevel;
	}

	@Column(name = "REPEAT_CONSUME_LEVEL", length = 10)
	public String getRepeatConsumeLevel() {
		return this.repeatConsumeLevel;
	}

	public void setRepeatConsumeLevel(String repeatConsumeLevel) {
		this.repeatConsumeLevel = repeatConsumeLevel;
	}

	@Column(name = "REWARD_STATUS", length = 10)
	public String getRewardStatus() {
		return this.rewardStatus;
	}

	public void setRewardStatus(String rewardStatus) {
		this.rewardStatus = rewardStatus;
	}

	@Column(name = "fqa_answer", length = 4000)
	public String getFqaAnswer() {
		return this.fqaAnswer;
	}

	public void setFqaAnswer(String fqaAnswer) {
		this.fqaAnswer = fqaAnswer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
	@Transient
	public Date getCreateTime2() {
		return this.createTime2;
	}

	public void setCreateTime2(Date createTime) {
		this.createTime2 = createTime;
	}

}
