package shop.company.entity;

// Generated 2010-12-10 13:23:34 by Hibernate Tools 3.4.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemDbBackup generated by hbm2java
 */
@Entity
@Table(name = "system_db_backup")
public class SystemDbBackup implements java.io.Serializable {

	private Integer bkId;
	private Date bkTime;
	private String bkTitle;
	private String bkPath;
	private String bkComment;

	public SystemDbBackup() {
	}

	public SystemDbBackup(Date bkTime, String bkTitle,String bkPath, String bkComment) {
		this.bkTime = bkTime;
		this.bkTitle = bkTitle;
		this.bkPath = bkPath;
		this.bkComment = bkComment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bk_id", nullable = false)
	public Integer getBkId() {
		return this.bkId;
	}

	public void setBkId(Integer bkId) {
		this.bkId = bkId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bk_time", length = 19)
	public Date getBkTime() {
		return this.bkTime;
	}

	public void setBkTime(Date bkTime) {
		this.bkTime = bkTime;
	}

	@Column(name = "bk_title", length = 50)
	public String getBkTitle() {
		return this.bkTitle;
	}

	public void setBkTitle(String bkTitle) {
		this.bkTitle = bkTitle;
	}

	@Column(name = "bk_comment")
	public String getBkComment() {
		return this.bkComment;
	}

	public void setBkComment(String bkComment) {
		this.bkComment = bkComment;
	}

	@Column(name = "bk_path")
	public String getBkPath() {
		return this.bkPath;
	}

	public void setBkPath(String bkPath) {
		this.bkPath = bkPath;
	}
	
}
